version: '3'
services:
  back:
    environment:
      - DOCKER=true
    image: node
    ports:
      - '4567:4567'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    working_dir: /usr/app/
    command: 'sh -c "npm i && npm run-script migrate && npm start"'
    depends_on:
      - postgres
    network_mode: host
  postgres:
    image: postgres:10.6-alpine
    ports:
      - '5432:5432'
    network_mode: host
